### ISSUE TITLE
FR1. Navigation Bar

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#1]
|FR1.  Navigation Bar|
|---|
|**Goal**: System will allow user to toggle between the contacts, appointments/calendar, and inventory sections of the application. |
| **Stakeholders:** Business Owner |
| **Description:** When the owner uses the application, there will be a stationary menu that resides on the top of the page.  This menu will have three tabs to click on: Calendar, Inventory Tracker, Contacts.  When the user clicks on the calendar tab, she/he will be directed to a web page where the calendar function of the application exists. When the user clicks on the inventory tracker tab of the menu, she/he will be directed to a web page where the inventory tracker function of the application exists. When the user clicks on the contacts tab, she/he will be directed to a web page with a table filled with the business owners contacts. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2019|  
|**Priority:** 2 |

**Comment by gp7633** [comment]
Created the IActionResult functions Calendar, and Inventory in Homecontroller.cs

**Comment by gp7633** [comment]
Created Calendar.cshtml and Inventory.cshtml for the navigation bar tabs

**Comment by gp7633** [comment]
Modified Privacy.cshtml so that it says "Contacts" instead of "Privacy"

**Comment by gp7633** [comment]
In _Layout.cshtml changed the link from Privacy to Contacts. Also added controllers for the calendar and inventory navigation items

**Comment by gp7633** [comment]
Deleted Privacy.cshtml for redundancy
