### ISSUE TITLE
FR15.  Update contact 

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#16]
| FR15.  Update contact |
| --- |
|**Goal**: The system will allow a user to update and edit a contact. |
| **Stakeholders:** Business Owner |
| **Description:** When a business owner would like to update or edit a contact this will allow them to do so. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |
| **Version:** 1.0 |
| **Date:** 09/22/2020 |
| **Priority:** 2 |

**Comment by JamesPallis** [comment]
clientDbInitializer was created to initialize the clientContact entity so we can get the entity created so that we can later update it

**Comment by JamesPallis** [comment]
From the clientContact entity a scaffolded item which is the clientContactsController which gives us CRUD functions to manipulate the clientContact entity

**Comment by JamesPallis** [comment]
Edit button on page allows to update any row in the clientContact entity
