### ISSUE TITLE
NR5: Availability

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#20]
| NR5: Availability |
| --- |
|**Goal**: The system will be accessible for all devices that have access to a web browser. |
| **Stakeholders:** All |
| **Description:** Accessibility and availability are important features because if nobody can get to our web application then it will not be usable or functional. By making this web browser we can make it accessible to anyone with internet. We will have our CRM available to people on any device capable of Wi-Fi or data connection.  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |
| **Version:** 1.0 |
| **Date:** 09/22/2020 |
| **Priority:** 1 |

**Comment by hmehryar** [comment]
Add "Feature" to all other requirements also

**Comment by KennOHanlon** [comment]
Upon pushing this project out to production, this site would be assessible to anyone who created an account which would mean that another functional requirement for creating an account would need to be generated and an entity managing user accounts would allow for this information to be stored. Each time a user logged in they would have access to the site.
