### ISSUE TITLE
FR16.  Creation of Inventory Entity

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#24]
|FR16.  Creation of Inventory Entity|
|---|
|**Goal**: Separate the items in business inventory from the items in the products inventory and allow them to be managed separately|
|**Stakeholders:** Business Owner|
| **Description:** Creating a separate entity for Inventory instead of only having a Products entity. This will allow for manipulation of an Inventory independently from Products. |
| **Origin:** Based on team meeting discussing about the item deletion from the product entity and needing a separation of controls for items in inventory|
| **Version:** 1.0  |
|**Date:** 11/4/2020| 
|**Priority:** 2 |

**Comment by JamesPallis** [comment]
Transitioning In stock and Restock values to Inventory Entity instead of Product Entity. This is better to house the the products that are in house for a business instead of total products in store and past ordered and out of stock all being in one place.

**Comment by JamesPallis** [comment]
Entity is created now must create Inventory Scaffolded Item in creating InventoryController.cs to manage the entity

**Comment by JamesPallis** [comment]
Planning to add a new issue to sprint 3 to develop the connectivity with products entity now that the creation of the inventory entity is done
