### ISSUE TITLE
FR17.  Front End Development for Appointment Entity

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#25]
|FR17.  Front End Development for Appointment Entity|
|---|
|**Goal**: Make entering information for appointments aesthetically pleasing.|
|**Stakeholders:** Business Owner|
| **Description:** The Appointment table and its corresponding views look fairly rough after creation of the backend to support CRUD operations. These views will be revisited to make a pleasing couple pages to edit information relating to appointments. |
| **Origin:** Based on CRUD operation creation of the Appointment entity|
| **Version:** 1.0  |
|**Date:** 11/6/2020| 
|**Priority:** 2 |

**Comment by mbratby** [comment]
Updated the front end for the products view first. Finishing the appointment entity next.

**Comment by mbratby** [comment]
Updated the services entity front end with better labels.

**Comment by mbratby** [comment]
Updated appointment entity labels, ready for review.
