### ISSUE TITLE
FR3.  Update Item/Restock Amount/Value

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#3]
|FR3.  Update Item/Restock Amount/Value|
|---|
|**Goal**: System will allow users to update values for a pre-existing item in the inventory tracker table. |
|**Stakeholders:** Business Owner|
| **Description:** This function will allow users to click on an item in the inventory tracker table. When the item in the table is selected, the user will have a button at the top of the inventory tracker table that when clicked will pop up a form with the values for the selected item’s restock value and the sell price and buy price and amount of that item currently in stock.  These values will be held in editable text fields that the user can retype the correct or updated value in. Once the correct value has been inserted into the field(s), a button to update the inventory tracker will push the changes to the inventory tracker table, another button that when clicked will discard any changes. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2019| 
|**Priority:** 2 |

**Comment by JamesPallis** [comment]
Working with the Products MVC components to give us access to CRUD operations to get inventory value to be updatable

**Comment by JamesPallis** [comment]
Went back in to this issue to fix the front end functionality to make it present to the User better

**Comment by JamesPallis** [comment]
Front End and Back End fully functional
