### ISSUE TITLE
FR6: Calendar display daily

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#6]
| **FR6:** Calendar display daily |
| --- |
| **Goal:** The system will allow the artist/stylist to view all appointments for a specific day. |
| **Stakeholders:** Business Owner |
| **Description:** After a customer has an appointment added to the schedule, the artist or stylist need a way to be able to view the appointments that have been assigned to them.  This feature would allow all appointments scheduled on the selected day to be viewed in chronological order, showing the artist the customers name and simple details about the appointment. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |	
| **Version:** 1.0 }
| **Date:** 9/22/2020 |
| **Priority:** 2 |

**Comment by JamesPallis** [comment]
Gathered information about how to implement a daily calendar. Started initial implementation by refactoring the appointment model to give DateTime data type instead of 2 separate fields for Date and Time.

**Comment by JamesPallis** [comment]
Had to delete DB and connections and rescaffold appointment controller and views to get the database to update. All is running smoothly now to start implementing the daily calendar.

**Comment by JamesPallis** [comment]
Had issues implementing trying to use tag helpers going for a different Javascript approach now

**Comment by JamesPallis** [comment]
Daily Calendar added to Home Page just have to work on loading the appointment data into it upon execution

**Comment by JamesPallis** [comment]
Tried using DayPilot nuget package but could not figure out connectivity with our calendar or appointment controller and it caused my program to not run so I reverted changes back to the last commit. Doing more research now

**Comment by JamesPallis** [comment]
Calendar Daily Display is up on the home page. All css formatting and html creation of the calendar is functional. If the project was moving forward I would have liked to connect it to our database to have real time appointment loading, however upon trying to implement this back end I ran into issues that would require another sprint to complete and more FRs to be made.
