### ISSUE TITLE
FR9: Remove appointment 

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#7]
| **FR9:** Remove appointment |
|---|
| **Goal:** Clients need to be able to be removed from the schedule as easily as they are added. |
| **Stakeholders:** Business Owner |
| **Description:** Just like how a client will look to book an appointment with a business, some may also need to cancel an existing appointment. The artists need to be able to remove and existing appointment from the calendar, which will put that time slot back into the pool of available times. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |
| **Version:** 1.0 |
| **Date:** 9/22/2020 |
| **Priority:** 2 |

**Comment by gp7633** [comment]
Started Development of Functioning Requirement

**Comment by gp7633** [comment]
Created Appointment.cs Model, and added a few properties to it which I believe the entity would have subject to change more from me and potentially others

**Comment by gp7633** [comment]
Created Appointment Controller along with created the Views for the Appointments. Modified contactContext.cs to be able to handle Appointments (Not pushed yet). Checking with teammates to see if that is what should be done, and making sure that it is similar to the other Databases/Entities

**Comment by gp7633** [comment]
Stashed all changes to review other parts of products, as well as updating the project for the next meeting, which will be November 6th at 7pm

**Comment by gp7633** [comment]
Created foreign keys for Appointment.cs allowing a connection between ClientContact.cs and Services.cs

**Comment by gp7633** [comment]
Pushed information from the comment earlier "Created Appointment Controller along with created the Views for the Appointments. Modified contactContext.cs to be able to handle Appointments (Not pushed yet). Checking with teammates to see if that is what should be done, and making sure that it is similar to the other Databases/Entities"

**Comment by gp7633** [comment]
Took over FR8, since MVC development allows creation and deletion at the same time when developing controllers

**Comment by gp7633** [comment]
Created Database for the appointments

**Comment by gp7633** [comment]
Modified Tabs in Navigation Bar to allow appointments option
