### ISSUE TITLE
FR7: Calendar display weekly

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#8]
| **FR7:** Calendar display weekly |
|---|
| **Goal:** The system will display the entire week and show the amount of appointments currently scheduled. | 
| **Stakeholders:** Business Owner |
| **Description:** Similar to the daily calendar view, but modifying the time frame to show the entire week. Artist will be able to look ahead at the upcoming week to view the number of appointments currently scheduled for each day.
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |
| **Version:** 1.0 |
| **Date:** 9/22/2020 |
| **Priority:** 2 |

**Comment by mbratby** [comment]
Creating weekly calendar view underneath daily view. Investigating adding a button to swap between views, saving space on the home page.

**Comment by mbratby** [comment]
Weekly calendar is complete. Having formatting issues with a few columns.

**Comment by mbratby** [comment]
Committing my code for the weekly calendar. Mimicked the style of the daily calendar and utilized James' css code for format. Having the same issue as James when trying to link the calendar to the database. Data is hard coded into the table but Sunday column is formatting incorrectly.
