### ISSUE TITLE
FR8: Add appointment

### ISSUE THREAD

**Issue by KennOHanlon** [WSU-4110/Orgnzr#9]
| **FR8:** Add appointment |
|---|
| **Goal:** The system should allow the artist/stylists to add a customer to a specific day and time. |
| **Stakeholders:** Business Owner |
|**Description:** Being able to add customers to the calendar is key to this program's functionality. When a customer is looking to book an appointment, the business needs to be able to add that customer to a specific day and time slot that is currently unallocated using the calendar functionality. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |
| **Version:** 1.0 |
| **Date:** 9/22/2020 |
| **Priority:** 1 |

**Comment by mbratby** [comment]
Assigned functioning requirement on 10/27, starting work on 10/28.

**Comment by gp7633** [comment]
Started development on FR8 since with MVC adding and deleting will fall under the same controller creation

**Comment by gp7633** [comment]
Developed at the same time as FR9: Remove Appointment

**Comment by gp7633** [comment]
Created Appointment.cs Model, and added a few properties to it which I believe the entity would have subject to change more from me and potentially others

**Comment by gp7633** [comment]
Created/Pushed Appointment Controller along with created the Views for the Appointments. Modified contactContext.cs to be able to handle Appointments

**Comment by gp7633** [comment]
Created foreign keys for Appointment.cs allowing a connection between ClientContact.cs and Services.cs

**Comment by gp7633** [comment]
Created Database for the appointments

**Comment by gp7633** [comment]
Modified Tabs in Navigation Bar to allow appointments option

**Comment by gp7633** [comment]
Added question mark to the appointment entity to allow the business owner to create a contact while creating an appointment, subject to change and make better for this is not part of the functioning requirement
